spring.profiles.active=prod

# logging
# Package-specific log level
logging.level.com.next.move.MoveApplication=DEBUG
# Disable almost everything
logging.level.root=WARN
logging.file.name=app.log

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

twilio.opt.out1=PAUSE
twilio.opt.out2=STOP
twilio.opt.in1=START
twilio.opt.in2=RESTART
twilio.opt.out.reply=Your goal has been paused. You will not receive further messages from NxMove. Reply START anytime to resume your goal.
twilio.opt.in.reply=Your goal has been restarted. You will now receive messages from NxMove. Reply PAUSE to stop messages anytime.